### ISSUE TITLE
solr indexing issue with intra-american variable

### ISSUE THREAD

**Issue by JohnMulligan** [rice-crc/voyages#76]
The variable's name has been changed as we move to PAST:

- current build:
- is_intra_american (sql)
- var_intra_american_voyage (solr)

- PAST
- dataset

Currently, my dev branch solr build at least isn't finding the is_intra_american variable on the dev branch. Reindex fails:

`haystack     ERROR    Failed to add documents to Solr: Solr responded with an error (HTTP 400): [Reason: ERROR: [doc=voyage.voyage.1] unknown field 'var_intra_american_voyage']
Traceback (most recent call last):
  File "/root/.local/lib/python2.7/site-packages/haystack/backends/solr_backend.py", line 76, in update
    self.conn.add(docs, commit=commit, boost=index.get_field_weights())
  File "/root/.local/lib/python2.7/site-packages/pysolr.py", line 1050, in add
    solrapi=solrapi,
  File "/root/.local/lib/python2.7/site-packages/pysolr.py", line 565, in _update
    "post", path, message, {"Content-type": "text/xml; charset=utf-8"}
  File "/root/.local/lib/python2.7/site-packages/pysolr.py", line 463, in _send_request
    raise SolrError(error_message % (resp.status_code, solr_message))
SolrError: Solr responded with an error (HTTP 400): [Reason: ERROR: [doc=voyage.voyage.1] unknown field 'var_intra_american_voyage']`

@dellamonica -- can you track down the breaking point here?

**Comment by JohnMulligan** [comment]
Human error. I was using a core from a different branch of the code without realizing it.

 [Data is persisted between restarts of the containers.](https://github.com/JohnMulligan/voyages/blob/develop/docs/development.md#is-data-persisted-between-restarts-of-the-containers)

**Comment by derekjkeller** [comment]
Closing.
